services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
